The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prizewinning data. And we encourage you then to explore further questions that you're interested in!

In [55]:
# Loading in required libraries
import pandas as pd
import seaborn as sns
import numpy as np

# Start coding here!

In [56]:
#Import data
nobel = pd.read_csv("data/nobel.csv")

In [57]:
pd.set_option('display.max_columns', None)
print(nobel.head())

   year    category                                           prize  \
0  1901   Chemistry               The Nobel Prize in Chemistry 1901
1  1901  Literature              The Nobel Prize in Literature 1901
2  1901    Medicine  The Nobel Prize in Physiology or Medicine 1901
3  1901       Peace                      The Nobel Peace Prize 1901
4  1901       Peace                      The Nobel Peace Prize 1901

                                          motivation prize_share  laureate_id  \
0  "in recognition of the extraordinary services ...         1/1          160
1  "in special recognition of his poetic composit...         1/1          569
2  "for his work on serum therapy, especially its...         1/1          293
3                                                NaN         1/2          462
4                                                NaN         1/2          463

  laureate_type                     full_name  birth_date         birth_city  \
0    Individual  Jacobus Henricus van 't Hoff  1852-08-30          Rotterdam
1    Individual               Sully Prudhomme  1839-03-16              Paris
2    Individual        Emil Adolf von Behring  1854-03-15  Hansdorf (Lawice)
3    Individual             Jean Henry Dunant  1828-05-08             Geneva
4    Individual                Frédéric Passy  1822-05-20              Paris

      birth_country   sex   organization_name organization_city  \
0       Netherlands  Male   Berlin University            Berlin
1            France  Male                 NaN               NaN
2  Prussia (Poland)  Male  Marburg University           Marburg
3       Switzerland  Male                 NaN               NaN
4            France  Male                 NaN               NaN

  organization_country  death_date death_city death_country
0              Germany  1911-03-01     Berlin       Germany
1                  NaN  1907-09-07   Châtenay        France
2              Germany  1917-03-31    Marburg       Germany
3                  NaN  1910-10-30     Heiden   Switzerland
4                  NaN  1912-06-12      Paris        France

**What is the most commonly awarded gender and birth country?**

In [58]:
top_gender = nobel["sex"].value_counts().idxmax()
print("The most gender is: ", top_gender)

The most gender is:  Male

In [59]:
top_country = nobel["birth_country"].value_counts().idxmax()
print("The most country is: ", top_country)

The most country is:  United States of America

**Which decade had the highest ratio of US-born Nobel Prize winners to total winners in all categories?**

In [60]:
nobel['decate'] = (nobel['year']//10)*10
max_decade_usa = nobel[nobel['birth_country'] == top_country].decate.value_counts().idxmax()
print(max_decade_usa)

2000

**Which decade and Nobel Prize category combination had the highest proportion of female laureates?**

In [61]:
nobel['female_winner'] = nobel['sex'] == 'Female'
df_female = nobel.groupby(['decate', 'category'], as_index=False)['female_winner'].mean()
df_female

    decate    category  female_winner
0     1900   Chemistry       0.000000
1     1900  Literature       0.100000
2     1900    Medicine       0.000000
3     1900       Peace       0.071429
4     1900     Physics       0.076923
..     ...         ...            ...
67    2020   Economics       0.111111
68    2020  Literature       0.500000
69    2020    Medicine       0.125000
70    2020       Peace       0.285714
71    2020     Physics       0.166667

[72 rows x 3 columns]

In [62]:
max_cat = df_female[df_female['female_winner'] == df_female['female_winner'].max()]
max_cat

    decate    category  female_winner
68    2020  Literature            0.5

In [63]:
max_female_dict= {max_cat.decate.values[0]:max_cat.category.values[0]}
max_female_dict

{2020: 'Literature'}

**Who was the first woman to receive a Nobel Prize, and in what category?**

In [64]:
first_w = nobel_female[nobel_female["year"]==nobel_female["year"].min()]
first_w

,year,category,prize,motivation,prize_share,laureate_id,laureate_type,full_name,birth_date,birth_city,birth_country,sex,organization_name,organization_city,organization_country,death_date,death_city,death_country,decate,female_winner
19,1903,Physics,The Nobel Prize in Physics 1903,"""in recognition of the extraordinary services ...",1/4,6,Individual,"Marie Curie, née Sklodowska",1867-11-07,Warsaw,Russian Empire (Poland),Female,NaN,NaN,NaN,1934-07-04,Sallanches,France,1900,True

In [65]:
first_woman_name = first_w.full_name.values[0]
first_woman_category = first_w.category.values[0]
print(first_woman_name ,first_woman_category)

Marie Curie, née Sklodowska Physics

**Which individuals or organizations have won more than one Nobel Prize throughout the years?**

In [66]:
counts = nobel['full_name'].value_counts()
repeat = counts[counts >= 2].index
repeat_list = list(repeat)